export const FETCH_ALL_CARS_PENDING = "FETCH_ALL_CARS_PENDING";
export const FETCH_ALL_CARS_SUCCESS = "FETCH_ALL_CARS_SUCCESS";
export const FETCH_ALL_CARS_FAILED = "FETCH_ALL_CARS_FAILED";

export const FETCH_ONE_CAR_PENDING = "FETCH_ONE_CAR_PENDING";
export const FETCH_ONE_CAR_SUCCESS = "FETCH_ONE_CAR_SUCCESS";
export const FETCH_ONE_CAR_FAILED = "FETCH_ONE_CAR_FAILED";

export const ADD_CAR_PENDING = "ADD_CAR_PENDING";
export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS";
export const ADD_CAR_FAILED = "ADD_CAR_FAILED";

export const REMOVE_CAR_PENDING = "REMOVE_CAR_PENDING";
export const REMOVE_CAR_SUCCESS = "REMOVE_CAR_SUCCESS";
export const REMOVE_CAR_FAILED = "REMOVE_CAR_FAILED";

export const EDIT_CAR_SUCCESS = "EDIT_CAR_SUCCESS";
export const EDIT_CAR_FAILED = "EDIT_CAR_FAILED";
export const EDIT_CAR_PENDING = "EDIT_CAR_PENDING";

export const BASE_URL = "http://localhost:8082/api/stealership/cars";
